import { z } from 'zod';

import { sanitizeText } from '../utils/sanitize';

/**
 * Request validation for the Product API. Every field that ends up in a
 * DynamoDB item or a derived index key (`name`, `description`, `categoryId`)
 * is sanitized via `.transform(sanitizeText)` as part of validation, so
 * unsanitized input never reaches the service or repository layer.
 *
 * `status` here must stay in sync with `PRODUCT_STATUSES` in
 * `src/domain/product.ts`.
 */

const MAX_PRICE_CENTS = 100_000_000; // $1,000,000.00 — a sanity ceiling, not a business rule.

const nameSchema = z
  .string()
  .trim()
  .min(1, 'name is required')
  .max(200, 'name must be at most 200 characters')
  .transform(sanitizeText)
  .refine((value) => value.length > 0, 'name must contain visible characters');

const descriptionSchema = z
  .string()
  .max(4000, 'description must be at most 4000 characters')
  .transform(sanitizeText);

const categoryIdSchema = z
  .string()
  .trim()
  .min(1, 'categoryId is required')
  .max(64, 'categoryId must be at most 64 characters')
  .regex(/^[^#]+$/, 'categoryId must not contain "#"')
  .transform(sanitizeText)
  .refine((value) => value.length > 0, 'categoryId must contain visible characters');

const priceCentsSchema = z
  .number({ invalid_type_error: 'priceCents must be a number' })
  .int('priceCents must be an integer')
  .nonnegative('priceCents must not be negative')
  .max(MAX_PRICE_CENTS, `priceCents must be at most ${MAX_PRICE_CENTS}`);

const currencySchema = z
  .string()
  .trim()
  .regex(/^[A-Za-z]{3}$/, 'currency must be a 3-letter ISO 4217 code')
  .transform((value) => value.toUpperCase());

const statusSchema = z.enum(['ACTIVE', 'DRAFT', 'ARCHIVED']);

// An S3 object key generated by `lib/s3.ts#generateObjectKey` (never
// client-named — see `schemas/upload.schema.ts`). Bounded loosely here;
// the real shape guarantee comes from the upload flow that produced it.
const imageKeySchema = z.string().trim().min(1).max(512);
const imageKeysSchema = z.array(imageKeySchema).max(10, 'at most 10 images per product');

export const productIdPathSchema = z.object({
  id: z.string().trim().uuid('id must be a valid UUID'),
});

export const listProductsQuerySchema = z.object({
  categoryId: z
    .string()
    .trim()
    .min(1)
    .max(64)
    .regex(/^[^#]+$/, 'categoryId must not contain "#"')
    .optional(),
  limit: z.coerce
    .number()
    .int('limit must be an integer')
    .positive('limit must be positive')
    .max(100)
    .optional(),
  cursor: z.string().trim().min(1).optional(),
});

/**
 * Admin-only listing additionally accepts `status`. Left off the public
 * `listProductsQuerySchema` deliberately: GSI1 partitions products by
 * status, so exposing it there would let an unauthenticated caller list
 * DRAFT/ARCHIVED products just by passing the query param. The admin route
 * that uses this schema is gated by `requireAdmin()`.
 */
export const adminListProductsQuerySchema = listProductsQuerySchema.extend({
  status: statusSchema.optional(),
});

export const createProductBodySchema = z.object({
  name: nameSchema,
  description: descriptionSchema.default(''),
  categoryId: categoryIdSchema,
  priceCents: priceCentsSchema,
  currency: currencySchema,
  status: statusSchema.optional(),
  imageKeys: imageKeysSchema.optional(),
});

export const updateProductBodySchema = z
  .object({
    name: nameSchema.optional(),
    description: descriptionSchema.optional(),
    categoryId: categoryIdSchema.optional(),
    priceCents: priceCentsSchema.optional(),
    currency: currencySchema.optional(),
    status: statusSchema.optional(),
    imageKeys: imageKeysSchema.optional(),
  })
  .refine((data) => Object.values(data).some((value) => value !== undefined), {
    message: 'At least one field must be provided',
  });

export type ProductIdPath = z.infer<typeof productIdPathSchema>;
export type ListProductsQuery = z.infer<typeof listProductsQuerySchema>;
export type AdminListProductsQuery = z.infer<typeof adminListProductsQuerySchema>;
export type CreateProductBody = z.infer<typeof createProductBodySchema>;
export type UpdateProductBody = z.infer<typeof updateProductBodySchema>;
